schema: amgi_v1
name: JLPT_N2_Frequent_Vocabulary_001
required_fields:
  - target
  - reading
  - meaning
  - context
  - translation
  - memo
optional_fields: []
global_tags:
  - JLPT
  - N2
  - FrequentVocabulary
templates:
  - name: Recall Meaning
    front: |
      <div class="target">{{target}}</div>
      <div class="reading">{{reading}}</div>
      <hr>
      <div class="context">{{context}}</div>
    back: |
      {{FrontSide}}
      <hr id=answer>
      <div class="reading">{{reading}}</div>
      <div class="meaning">{{meaning}}</div>
      <div class="translation">{{translation}}</div>
      <pre class="memo">{{memo}}</pre>
  - name: Recall Target
    front: |
      <div class="prompt prompt-ko">{{meaning}}</div>
      <hr>
      <div class="translation">{{translation}}</div>
    back: |
      {{FrontSide}}
      <hr id=answer>
      <div class="target">{{target}}</div>
      <div class="reading">{{reading}}</div>
      <div class="context">{{context}}</div>
      <pre class="memo">{{memo}}</pre>
